version: "3.5"
services:
  waf_syslog:
    image: syslog:latest
    command: cd /home/agent && python3 receiver_udp.py && /bin/bash insert.sh
    restart: always
    volumes:
      - /home/waf/syslog_files:/data/waf/syslog_files
      - /home/waf/script:/receiver
